baseURL = "http://cherylhsu.ca/"
languageCode = "en-ca"
title = "Cheryl Hsu"

theme = "anatole"
summarylength = 10
enableEmoji = true

[params]
title = "Cheryl Hsu"
author = "Cheryl Hsu"
description = "Designing With Dragons"
profilePicture = "images/shob.jpg"
  mainSections = ["post"]

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/cherylshoe"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/pages/about/"
